### PR TITLE
Helping users find known-good state of dependency resolution

### PR DESCRIPTION
**Pull request by patcon**
Just came across this and very interested in the possibility of using it as part of the upcoming City of Toronto Open Data Strategy, for which I am doing preliminary citizen research on tools.

Anyhow, I tried to install using the instructions given, and when entering "http://publicdata.eu" in response to first prompt, I'm immediately tossed out of the script with a "zero" status code.

I notice that you have all the packages.json dependencies unpinned (ie. set to latest). This can lead to reproducibility issues like this, where the world has moved on, and your app no longer works with the most recent versions of packages.

Might you be willing to explore your local machine and copy a pastebin of the output for `npm list`. That way, I could lock down the required packages and get this working

I would also recommend trying the `yarn` package manager. It's an alternative to `npm`, written by Facebook, which does dependency management more effectively (ie. it produces a "lockfile" than can be committed)

Anyhow, please feel free to let me know your thinking on this issue! Thanks for everything! :)

### CODE REVIEW

**Comment by patcon** [comment]
Interestingly, when I remove [this function definition](https://github.com/ahmadassaf/OpenData-Checker/blob/master/util/utils.js#L31) (leaving the contained code) and hardcode a valid CKAN instance, then I get to the menu. But then when I select an option, I'm booted out of the script again.

**Comment by patcon** [comment]
And I've tried with both zsh and bash, just to be safe.

**Comment by ahmadassaf** [comment]
Hello @patcon and thanks a lot for your feedback. Unfortunately i have not maintained this tool for a while but it seems like a good chance to do that now :) I will try to do that these days but for sure its going to be my little weekend project. 

For now, my local `package.json` is:

```javascript
{
  "name"         : "DatasetCrawler",
  "version"      : "0.0.8",
  "description"  : "Public Dataset Crawler",
  "main"         : "server.js",
  "author"       : "Ahmad.A.Assaf",
  "dependencies" : {
    "request"         : "^2.51.0",
    "cheerio"         : "^0.18.0",
    "async"           : "^0.9.0",
    "underscore"      : "^1.7.0",
    "validator"       : "^3.25.0",
    "inquirer"        : "^0.8.0",
    "mkdirp"          : "^0.5.0",
    "extend"          : "^2.0.0",
    "colors"          : "^1.0.3",
    "awesome-progress": "^0.0.53",
    "progress"        : "^1.1.8",
    "csv-parse"       : "^0.0.6"
  }
}
```

I hope that helps, but am planning a re-write soon as well. The tool was written in my early node days, i'd approach few things completely different now.

**Comment by patcon** [comment]
Thanks! If I get a chance, I'll submit a yarn lockfile and add an explanatory section to the README, just so that it's in the code :)

**Comment by patcon** [comment]
Woo! That got things working, so converted this to the PR :)

There are a few new stumbles, but I'll create new issues!

**Review by ahmadassaf — APPROVED** [review]

**Pull request merged**
